## GET all cats
GET http://localhost:5000/api/v1/cat

## GET one cat
GET http://localhost:5000/api/v1/cat/9592

## POST new cat
POST http://localhost:5000/api/v1/cat
Content-Type: application/json

{"cat_name": "Roshan", "weight": 7, "owner": 3611, "filename": "fluffy.jpg", "birthdate": "2022-03-15"}

## PUT update cat
PUT http://localhost:5000/api/v1/cat/9592
Content-Type: application/json

{"cat_name": "Roshan Updated", "weight": 12}

## DELETE cat
DELETE http://localhost:5000/api/v1/cat/9592